### PR TITLE
Fixes outbomb Cuban pete.

### LINKED ISSUE #127: Outbomb Cuban Pete only gives you an exceedingly shitty TTV bomb
**Problem Description**:
The bomb is shitty

**What did you expect to happen**: 
Me to get a normal syndie bomb, or a TTV with more gas then possible by normal gameplay.

**What happened instead**:
The o2 was at 20deg Celsius, plasma was at 600deg, both weren't above 1000kpa. Prolly mis-remembering the exact temp of plasma.

**Why is this bad/What are the consequences:**
Why risk getting gibbed, if all I get is a useless bomb?

**Steps to reproduce the problem**:
Emag arcade machine, win game, look at bomb, kill yourself.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
How do I shot web?

### PR DESCRIPTION
**Pull request by SgtxRootbeer**
:cl: hits
Fix: increased power from Cuban Pete's bombs
/:cl:
Fixes #127

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
RIP, will fix when I get home

**Comment by SgtxRootbeer** [comment]
God, I'm fucking autistic. However, editing on mobile is shit. I will re-open and fix later.

**Comment by SgtxRootbeer** [comment]
FUKKIT, WE'RE DOING IT LIVE!

**Comment by SgtxRootbeer** [comment]
Yay, it worked

**Comment by SgtxRootbeer** [comment]
Merge whenever you feel like it

**Comment by EvilJackCarver** [comment]
why are you pissed at me now

**Comment by SgtxRootbeer** [comment]
I'm not, I just saw the tag, lol'd and clicked it.

**Pull request merged**
