### PR TITLE
engineering re-factor and sec autolathe

### PR DESCRIPTION
**Pull request by SgtxRootbeer**
:cl: Hits-The-Wizard
add: autolathe in sec
tweak: extended Shield generator room west by 1 tile
tweak: moved FTL drive to shield gen room, and shifted shield gen up and to the right 1 tile each.
tweak: old FTL drive room is now auxiliary construction room, for engineering to put fun stuff in, like a gas turbine, or a burn chamber for their teg instead of relying on the SM shard to heat up the hot loop.
/:cl:
babby's first PR

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
suber-snab

**Comment by Pascal125** [comment]
The issue with that is the Limited space of the map. We don't exactly have huge populations, so i doubt it'd be much of a bottleneck. Personally. Maybe some changes could be done for the sake of convenience but... I'm not too sure about that, given the size of the map.

**Comment by SgtxRootbeer** [comment]
currently, i see 3 options here
1, i leave it as it is. which, is a pretty good idea, i already took into account the reduced space, which is why that side of the room has the wall made entire out of windows (excluding the corners and door). i wanted the piping to be visable, and to project a feeling of openness.
2, i could make that side of the room out of 1-way windows and windoors, but that doesnt fit with ship design too well.
3, i could compact the CE's room and the upper engine room to increase hallway space in that particular area, however, i feel like it would just make the hallway appear disjointed.
i put a relatively large amount of thought into this, in case you didnt know.

**Comment by EvilJackCarver** [comment]
What if you were to slide the room to the right, instead? You could move the porta-pump docks down to where the now-empty room is, or lower to where the gravgen is. That'd knock the main hall down to 2-wide, but it'd give the engineering a 2-wide corridor.

**Comment by SgtxRootbeer** [comment]
moving it to the right is possible, however, having a 2-tile wide central hallway may cause some ire, especially next to the bridge and hop office areas.
http://www.strawpoll.me/12073532
i'll check this in 30 minutes from time of posting

**Comment by EvilJackCarver** [comment]
Yeah, I can see how 2-wide would cause issues. 

Out of curiosity, how viable would an over/under setup where Atmos storage is be? I'd imagine 'not very', seeing as Atmos storage is 6-by-4, expanding it down would cut into the R&D window area; up would cut into gravgen.

I'm trying to avoid a 1-wide corridor as much as possible because it'd feel claustrophobic every time I'd have to go through that chokepoint.

Alternatively, what about switching it out with Engineering storage?

**Comment by Pascal125** [comment]
I'm personally fine with how it is... While it is not perfect, we do not really strive for complete  perfection. Imo, anyways. One could potentially add airlocks to each corner of the wedge with engineering access added to it. In order to make it seem like a maintenance access, except engineering; if that fixes any issue.

Is that room underneath just going to be empty? From what i gathered that was the plan, yes?
Feel free to disregard my responses here if they do not really assist in any way, as i am honestly the least cognitive in terms of Engineering and Atmospherics atm. :P

**Comment by SgtxRootbeer** [comment]
the idea is that the room, is engineering's cardboard box. they can put anything they want into it.
they can put a gas turbine in it, if rnd gets them the boards
they can make a burn chamber for the teg so you dont have to have the sm shard heat up the loop, allowing you to make a loop similar to delta, which can achieve super low temps, allowing multiple emitters being fired at the SM shard.
if you stop at the required space stations, the engineering dept could remove all of the floor and put in a mini tesla/singulo engine
if engineering decides they hate the captain, because condom, they could pretend they wanna make a tesla in the room, and instead point the pa literally at the bridge, and hold them hostage.


engineering is so boring, and its because our codebase is adopted from an older version of /tg/.
even now, /tg/ coderbus and admins are having trouble for engineering, as all they have to do is turn on the power breaker. this problem is reflected here too.
there is a saving grace however, with the power system being much, much less efficient and useful then /tg/'s, the engineering department has extrinsic motivation for upgrading the power generation system.
this gives engineering the space they need to make a large portion of those upgrades.

there is one other option, i could cut the engineering break room in half, move the gravity generator there, and move the ftl drive, or shield gen to the old grav-gen's location. it would be very painful to map, and would prolly take me a day to get it finished.

**Comment by EvilJackCarver** [comment]
Yeah, cutting engineering storage in half wouldn't work too well in the long run.

I'll dismiss my request for changes, and we'll see how big of an issue a one-wide corridor is in execution.

**Comment by SgtxRootbeer** [comment]
If anyone else has any objections, pm me on discord, or comment here. I will check it in 1 hour from time of posting. If no one objects, I will press the merge button.

**Comment by SgtxRootbeer** [comment]
i re-read discord and heard a lot of complaints about a lack of light replacers, so i'm bundling this into my PR.

**Comment by SgtxRootbeer** [comment]
since i heard no solid objections to this or its update... i will merge now

**Pull request merged**
