### PR TITLE
maintenance update, for basilisk

### PR DESCRIPTION
**Pull request by SgtxRootbeer**
:cl: hits, in a better mood
add: emag and gps, in a speshul place, for people with rcd's or tele-scientists.
fix: lighting in engineering
add: SM ejection button
/:cl:
i added the emag, so people can enable some parts of the ship (carpotoxin is a useful chem, despite popular belief, and without the emag, morphine is limited in supply) that normally dont get use without advanced badminnery (although, to say that doesnt happen on a regular basis, would be lying)

### CODE REVIEW

**Comment by Pascal125** [comment]
Not sure how i feel about the whole "Emag" in a "Speshul" place onboard the shuttle for people with "RCD's" and "tele-scientists".

Electromagnetic Cards are fairly powerful Syndicate technology that is quite clearly defined as contraband.
Why would it just be lying about somewhere onboard?

**Comment by SgtxRootbeer** [comment]
@pascal125
Nice waiting until after I go to bed.
Regardless, I added it because the emag has alternative functions that can be useful for the station.
Such as enabling useful Chems from the Chem dispenser, carding the comms console so the captain can swear at the syndicate after 2 ravagers turn his ship into Swiss cheese, giving cargo something to blow 400k points on, etc.
Francium gave me the suggestion for the location, due to the largely wasted space, and me wanting it to be hard to get. Anyone wanting it will have to use telescience, or go through 2 r-walls, or a live slime pen+ an r-wall.

**Comment by SgtxRootbeer** [comment]
I beg to differ, being able to produce tons of miner's salve would be fantastic, mainly because you can't OD on it. 
Rezadone, is still the preferred way of testing clone damage, for people who can't take cryo eg:Yati. (Believe me, I've died twice in /tg/ cryo, due to me being a slimeperson).
Also, rnd firing pins, (if we port it) synthetic armblades, from the limb grower, arcade machines (outbomb Cuban Pete), soda and booze dispenser, pacmans, sec gas masks, etc.

**Comment by SgtxRootbeer** [comment]
If you want, however, I can put this in the armory/hos locker/armory. Ironically, I believe this is more secure, however.

**Comment by SgtxRootbeer** [comment]
Holy mother of triple-post,
I will push a commit, and re-open this after Andreas' is merged.

**Pull request closed without merging**
