### PR TITLE
Basilisk update number whatever

### PR DESCRIPTION
**Pull request by EvilJackCarver**
:cl: EvilJackCarver
add: Added newscasters to bridge, locker room, bar, and head of staff offices.
add: Added a light per maint tunnel to maint tunnels (two for engi maint)
del: Removed Cassie Suthorn's locker; her return is unlikely.
tweak: Expanded the armoury. The AI core has been move to accomodate.
fix: Moved misplaced fire alarms.
add: paper bins
tweak: the plasma in xenobio is now a single stack instead of 4 stacks containing 1 plasma each.
/:cl:

### Don't-merge: Waiting for Hits to add in paper bins and edit this post with his part of the changelog.

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
extremely high chance of me having borked this, due to me having never done something like this before, and having to resolve some merge conflicts.
to that end, get ready to revert it, or yell at me to fix it with dmm later on.

**Comment by SgtxRootbeer** [comment]
i borked it. time to cry.

**Comment by EvilJackCarver** [comment]
***[CAN WE FIX IT?
YES WE CAN!](https://www.youtube.com/watch?v=os4W2CZcWS0)***

**Comment by SgtxRootbeer** [comment]
welp, considering it passes the holy grail that is travis, and it you seem to have fixed my incompetency.
i will merge it.

**Pull request merged**
