### PR TITLE
Replaces the Security/Medical consoles' internal printers with dot-matrix printers because it's obviously the 1980s

### PR DESCRIPTION
**Pull request by EvilJackCarver**
:cl: EvilJackCarver
soundadd: Medical and Security Records consoles now have a new dot-matrix printer installed, capable of approximately 10.9 sheets per minute!
/:cl:

*(Undocumented: Increased printer delay to 5.5 seconds [up from 3.0] to match up with the print cycle finishing. The sound is a second or so longer, as it also includes the printer head returning to the park position after the paper is spit out.)*

Volume comparison:
---
*Attached files:*
* [door_versus_dot_matrix_printer.zip](https://github.com/Pascal125/Faster-Than-Lizard-13/files/770315/door_versus_dot_matrix_printer.zip) *(946 KiB)*

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
wait, does this apply to printing wanted posters and whatnot from the comms/newscaster consoles too?

**Comment by EvilJackCarver** [comment]
***I DIDN'T TEST THAT***

**Comment by SgtxRootbeer** [comment]
also, what about
>library computers printing books/tomes
>photocopiers
>detective forensic scanners
>maybe circuit board printers?

**Comment by EvilJackCarver** [comment]
* They make their old sound, 
* they make their old sound, 
* they're still silent, 
* they're still silent.

**Pull request merged**
